name: Deploy Workflow
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4 
      - run: npm install
      - run: npm run build
      - run: echo $VITE_API_URL
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "dist/index.html,dist/assets"
            target: "./text-markup/frontend"